<a href="https://colab.research.google.com/github/yuniecorn-dev/esaa_assignment/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy Version:", np.__version__)
print("\nNumPy Configuration:")
np.show_config()

NumPy Version: 2.0.2

NumPy Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    com

#### 3. Create a null vector of size 10 (★☆☆)



In [3]:
zero_array = np.zeros((10), dtype='int32')
print(zero_array)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)


In [12]:
array = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(array.nbytes)
print(zero_array.nbytes)

48
40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
zero_array[4] = 1
print(zero_array)

[0 0 0 0 1 0 0 0 0 0]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
array1 = np.arange(start=10, stop=50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
array2 = array1[::-1]
print(array2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
array1d = np.arange(9)
array3d = array1d.reshape(3,3)
print(array3d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
array3 = np.array([1,2,0,0,4,0])
array4 = array3[array3 != 0]
print('array3 == 0 불린 인덱싱 결과 값:', array4)

array3 == 0 불린 인덱싱 결과 값: [1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [19]:
# np.identity()
i_matrix = np.identity(3)
print(i_matrix)

#np.eye()
e_matrix = np.eye(3)
print(e_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [20]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.33628719 0.78231281 0.80218741]
  [0.00159714 0.22634915 0.02253026]
  [0.69195551 0.5032386  0.16859334]]

 [[0.04829419 0.29960182 0.46898332]
  [0.37004457 0.71986067 0.28321618]
  [0.10446701 0.03677022 0.19715496]]

 [[0.65158993 0.93485445 0.35665689]
  [0.31447184 0.86247764 0.09504769]
  [0.16246493 0.06636795 0.74989222]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [21]:
random_array2 = np.random.random((10,10))
print(f"최솟값: {random_array2.min()}")
print(f"최댓값: {random_array2.max()}")

최솟값: 0.0005838080925201217
최댓값: 0.991472199349415


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [22]:
random_vector = np.random.random(30)
print(f"평균값: {random_vector.mean()}")

평균값: 0.5235798611132996


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
z = np.ones((10,10))
z[1:-1:, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

- 정의되지 않은 값(nan)과의 모든 산술 연산은 nan이다.
- NaN은 자기 자신을 포함하여 어떤 값과도 같지 않다고 정의되어 있다.
- NaN과의 모든 비교 연산(>, <, == 등)은 항상 False이다.
- nan이 포함된 연산의 결과는 항상 nan이다.
- 파이썬의 set이나 dict는 객체의 동일성을 먼저 확인하기 때문에 포함된 것으로 간주한다.
- 이진법을 사용하는 컴퓨터의 부동 소수점 오차 때문이다. (실제 3 * 0.1은 0.30000000000000004가 된다.)

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [24]:
D = np.diag(1 + np.arange(4), k=-1)
print(D)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [25]:
C = np.zeros((8,8), dtype=int)
C[1::2, ::2] = 1 # 인덱스 1부터 끝까지 2칸 간격
C[::2, 1::2] = 1
print(C)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [27]:
R = np.unravel_index(100, (6,7,8))
print(R)

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [28]:
random_matrix = np.random.random((5,5))

Z = (random_matrix - random_matrix.mean()) / random_matrix.std()
print(Z)

[[-0.53627184 -0.67127306 -1.14986585  1.5295382   0.16771633]
 [-0.25274691  0.64011473 -1.08416511  1.67046997  1.36627136]
 [-1.13377695  0.84366084 -1.42473556 -0.13470577 -0.00449444]
 [-0.34044314 -1.11295053  1.31116091  1.61183752  0.38934969]
 [-1.32730514  0.36834769 -1.10112192  0.96771814 -0.59232916]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [4]:
color_dtype = np.dtype([("r", np.ubyte),
                        ("g", np.ubyte),
                        ("b", np.ubyte),
                        ("a", np.ubyte)])

red_color = np.array((255, 0, 0, 255), dtype=color_dtype)

print(f"데이터 타입: {color_dtype}")
print(f"색상 값: {red_color}")
print(f"Red 채널 값만 확인: {red_color['r']}")

데이터 타입: [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
색상 값: (255, 0, 0, 255)
Red 채널 값만 확인: 255


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [8]:
# column 3

In [9]:
# column 2


In [10]:
# column 3
