<a href="https://colab.research.google.com/github/yuniecorn-dev/esaa_assignment/blob/main/YB_0306_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

In [16]:
array1 = np.random.random((5,3))
array2 = np.random.random((3,2))

array3 = np.dot(array1, array2)

print(array3)

[[0.10087611 0.27455862]
 [0.42577964 1.16663075]
 [0.2400834  0.67305011]
 [0.34569257 0.88567276]
 [0.32723816 0.9242909 ]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
import numpy as np
array1d = np.arange(start=1, stop=11) # 1~10까지의 배열 생성
array1d[(array1d>3) & (array1d<8)] *= -1  # 3~8사이의 값은 음수처리
print(array1d)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

```python
9
10 # np.sum(데이터, axis(축))으로 성질이 바뀜. -1은 '마지막 축(방향)을 기준으로 더해라'는 뜻이 됨. (0+1+2+3+4)
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

```python
Z**Z: Z의 Z제곱. (legal)

2 << Z >> 2: 비트(Bit) 이동 연산자. (legal)

Z <- Z: Z가 -Z보다 작은가?를 묻는 조건문. Z < (-Z)로 해석되어 True/False 배열을 반환.

1j*Z: 복소수 1j를 곱하는 연산. (legal)

Z/1/1: 1로 두 번 나누는 연산. (legal)

Z < Z > Z : (illegal)

(Z < Z) and (Z > Z)로 해석.
넘파이 배열끼리의 비교 결과는 [True, False, False...] 같은 배열로 나오는데, 배열 전체를 and로 하나로 묶어 평가할 수 없기 때문에 모호하다며 에러를 뱉어냄.
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

- nan: 0 나누기 0
- 0: 0 나누기 0의 몫은 0 반환으로 설계되어 있음.
- 거대한 음수 값: NaN은 실수로 취급되는데 정수로 바꾸려 하면 컴퓨터가 혼란스러워 함.

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [23]:
# 0~9 사이의 임의의 정수 10개를 가진 배열 2개 생성
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)

[9 4 7 5 9 4 6 8 2 0]
[2 4 4 3 5 5 9 0 5 0]


[0 3 6 7 9]

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [24]:
print(np.sqrt(-1))       # 결과: nan
print(np.emath.sqrt(-1)) # 결과: 1j(복소수)

nan
1j


/tmp/ipykernel_151/1559038241.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))       # 결과: nan


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [9]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [10]:
A = np.ones(3)*1 # [1. 1. 1.]
B = np.ones(3)*2 # [2. 2. 2.]

np.add(A, B, out=B)      # B = A + B
np.divide(A, 2, out=A)   # A = A / 2
np.negative(A, out=A)    # A = -A
np.multiply(A, B, out=A) # A = A * B

print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [11]:
# 0부터 10 사이의 소수를 포함한 양수 10개 생성
Z = np.random.uniform(0, 10, 10)
print(Z)

# method 1
print(Z - Z % 1)
# method 2
print(Z // 1)

[9.55530726 1.3143064  4.30748108 0.69638644 1.66878088 0.56462488
 8.23950797 0.89911024 1.93500855 4.09863748]
[9. 1. 4. 0. 1. 0. 8. 0. 1. 4.]
[9. 1. 4. 0. 1. 0. 8. 0. 1. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.12593807 0.28746818 0.38650341 0.47652247 0.50348914 0.51951839
 0.72224713 0.77323887 0.82856149 0.94030666]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [15]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A, B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [25]:
Z = np.random.random((10,2))

# 슬라이싱으로 X좌표(0번째 열)와 Y좌표(1번째 열) 분리
X = Z[:, 0]
Y = Z[:, 1]

# R 계산
R = np.sqrt(X**2 + Y**2)

# Theta 계산
T = np.arctan2(Y, X)

print(R)
print(T)

[0.70240665 0.95330803 0.47082652 0.98404101 0.99154739 0.7533054
 0.93333432 0.83076181 0.39167093 0.54764266]
[1.49054635 1.56688903 0.45646179 0.21329694 0.09861103 0.12541598
 0.47974275 0.62090703 0.5920537  0.3646271 ]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [26]:
Z = np.random.random(10)
print(Z)

Z[Z.argmax()] = 0
print(Z)

[0.6934295  0.93293324 0.67733208 0.01623649 0.91602939 0.66779936
 0.45387604 0.39376362 0.8343213  0.64918322]
[0.6934295  0.         0.67733208 0.01623649 0.91602939 0.66779936
 0.45387604 0.39376362 0.8343213  0.64918322]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [27]:
Z = np.arange(100)
v = np.random.uniform(0,100)

distances = np.abs(Z - v)  # Z의 모든 원소에서 v를 뺀 후 절댓값(거리)을 구함
closest_index = distances.argmin() # 거리 가장 짧은 곳의 인덱스
print(Z[closest_index])

18


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [28]:
Z = np.arange(9).reshape(3, 3)

# 넘파이의 다차원 enumerate (ndenumerate)
for index, value in np.ndenumerate(Z):
  print(f"위치 {index}의 값: {value}")

위치 (0, 0)의 값: 0
위치 (0, 1)의 값: 1
위치 (0, 2)의 값: 2
위치 (1, 0)의 값: 3
위치 (1, 1)의 값: 4
위치 (1, 2)의 값: 5
위치 (2, 0)의 값: 6
위치 (2, 1)의 값: 7
위치 (2, 2)의 값: 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [30]:
n = 5
p = 3

Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)

print(Z)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [31]:
Z = np.random.randint(0, 10, (3, 3))
print(Z)

[[0 0 6]
 [2 0 8]
 [2 5 2]]


In [33]:
# Z[:, n]으로 기준 열만 떼어낸 뒤, argsort()로 순서표(인덱스)를 얻음
# 그 순서표를 전체 Z 배열의 행 위치에 넣어줌 (팬시 인덱싱)
n =1
sorted_Z = Z[Z[:, n].argsort()]
print(sorted_Z)

[[0 0 6]
 [2 0 8]
 [2 5 2]]
